#!/bin/sh
# Usage
#
# cmd/fixt -w-up -s ptt

CMD="\033[0;36mcmd/fixit\033[0m";
FS_ROOT="$(pwd)"
FS_FXT=${FS_ROOT}/fxt
FS_W=;
LN=$(cat $FS_ROOT/cmd/fix.tpl)

cat_in() {
  FS_IN=${FS_FXT}/in
  cd $FS_IN;  
  echo "${CMD}.IN ${FS_IN}"
  IN="module.exports = { noop: \`"
  for f in $(ls -f *); do
    IN+=$LN
    IN+="$f': \`$(cat $f)"
  done
  IN+=$(printf "\` };")
  printf "%s" "$IN" > $FS_FXT/in.md.js  
}

cat_up() {
  FS_UP=${FS_FXT}/up  
  cd $FS_UP;
  echo "${CMD}.UP ${FS_UP}"
  UP="module.exports = { noop: \`"
  for f in $(ls -f *); do
    UP+=$LN
    UP+="$f': \`$(cat $f)"
  done
  UP+=$(printf "\` };")
  printf "%s" "$UP" > $FS_FXT/up.md.js
}

if [[ $1 != '' ]] ; then
  FS_FXT=${FS_FXT}/set/$1
fi 

# if [[ $1 = '-w-in' ]] ; then
#   CAT_W=cat_in
#   FS_W=${FS_FXT}/in
#   cat_up  
# elif [[ $1 = '-w-up' ]] ; then
#   CAT_W=cat_up
#   FS_W=${FS_FXT}/up
#   cat_in  
# else
#   cat_up
#   cat_in  
# fi

# if [[ $2 != '' ]] ; then
  echo "${CMD}.WATCH ${FS_FXT}"
  chsum1=""
  chsum3=""  
  while [[ true ]] ; do
    chsum2=`find ${FS_FXT}/in -type f -exec md5 {} \;`
    chsum4=`find ${FS_FXT}/up -type f -exec md5 {} \;`    
    if [[ $chsum1 != $chsum2 ]] ; then
      cat_in  
      chsum1=$chsum2
    fi
    if [[ $chsum3 != $chsum4 ]] ; then
      cat_up
      chsum3=$chsum4
    fi
    sleep 2
  done
# fi
